repos:
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v4.0.1
    hooks:
      ### Default checks (https://github.com/pre-commit/pre-commit-hooks/blob/main/.pre-commit-hooks.yaml)
      # Git checks
      - id: check-added-large-files
      # - id: no-commit-to-branch
      - id: check-merge-conflict
      # General file checks
      - id: destroyed-symlinks
      - id: check-vcs-permalinks
      - id: detect-private-key
      - id: end-of-file-fixer
        exclude: .idea/.*
      - id: fix-byte-order-marker
      - id: mixed-line-ending
      - id: trailing-whitespace
      # Data format checks
      - id: check-json
      # - id: pretty-format-json
      - id: check-toml
      - id: check-xml
      - id: check-yaml
        args: ["--unsafe"] # Needed for some tags in `mkdocs.yml`
      # Python specific checks
      - id: check-ast
      - id: check-builtin-literals
      - id: check-case-conflict
      - id: check-docstring-first
      - id: check-executables-have-shebangs
      - id: check-shebang-scripts-are-executable
      - id: debug-statements
      - id: fix-encoding-pragma

  ### Python specific tools
  - repo: local
    hooks:
      - id: ruff
        name: ruff
        description: lints python code.
        entry: poetry run ruff check
        require_serial: true
        language: system
        types: [python]
        args: [--fix, --exit-non-zero-on-fix]

      - id: black
        name: black
        description: formats python code.
        entry: poetry run black
        language: system
        types_or: [python]

      - id: isort
        name: isort
        description: sorts python imports.
        entry: poetry run isort
        language: system
        types_or: [python]

      - id: mypy
        name: mypy
        description: statically analyses python type annotations.
        entry: poetry run mypy
        language: system
        types: [python]
        #      args: [ --namespace-packages, --explicit-package-bases ]
        require_serial: true

      - id: vulture
        name: vulture
        description: finds unused python code.
        language: system
        entry: poetry run vulture
        types: [python]
        pass_filenames: false

      - id: bandit
        name: bandit
        description: finds common python security issues.
        entry: poetry run bandit
        language: system
        types: [python]
        args: [-c, pyproject.toml]
